#!/bin/bash
source activate neutronicsworkshop
mkdir -p ~/nuclear_data

# Download and extract ENDF/b 8.0 chain file with the SFR branching ratios to ~/nuclear_data/chain-endf-b8.0.xml
# TODO replaced with TENDL FNS chain or add FNS branching ratios as to ENDF/b 8.0 chain option
download_chain -l endf -r b8.0 -b SFR -d ~/nuclear_data -f chain-endf-b8.0.xml

# Download and extract ENDF/b 8.0 cross section files
wget -q -O - https://anl.box.com/shared/static/uhbxlrx7hvxqw27psymfbhi7bx7s6u6a.xz | tar -C ~/nuclear_data -xJ
mv ~/nuclear_data/endfb-viii.0-hdf5/* ~/nuclear_data

# Download and extract WMP Library
wget https://github.com/mit-crpg/WMP_Library/releases/download/v1.1/WMP_Library_v1.1.tar.gz -O ~/nuclear_data/WMP_Library_v1.1.tar.gz
tar -xzf ~/nuclear_data/WMP_Library_v1.1.tar.gz -C ~/nuclear_data