FROM openmcworkshop/openmc_workshop_image_repository:latest

# Python libraries used in the workshop
RUN pip3 install plotly
RUN pip3 install tqdm
RUN pip3 install ghalton==0.6.1
RUN pip3 install noisyopt
RUN pip3 install inference-tools

#installs VS code which is an IDE (Integrated development environment) for code
RUN wget https://update.code.visualstudio.com/1.34.0/linux-deb-x64/stable
RUN dpkg -i stable 
RUN apt-get --yes install -f
RUN echo 'function coder() { code "$1" --user-data-dir; }' >> ~/.bashrc
#installs python and docker exstentions for syntax highlighting and hinting
RUN code "$1" --user-data-dir  --install-extension ms-python.python
RUN code "$1" --user-data-dir  --install-extension tht13.python
RUN code "$1" --user-data-dir  --install-extension ms-azuretools.vscode-docker
RUN code "$1" --user-data-dir  --install-extension ms-vscode.sublime-keybindings

#installs FreeCAD
RUN apt-get install -y software-properties-common 
RUN add-apt-repository ppa:freecad-maintainers/freecad-stable
RUN apt-get update 
RUN apt-get --yes install freecad 
RUN ln -s /usr/lib/freecad/Mod /usr/lib/freecad-python3/Mod
RUN echo redown3

RUN git clone https://github.com/openmc-dev/plotter.git

RUN git clone https://github.com/ukaea/openmc_workshop

# Compile parametric plasma source
RUN cd /openmc_workshop/parametric_plasma_source && bash compile.sh
# source_sampling.so is the compiled plasma source so this copies it to various task folders for later use
RUN cp /openmc_workshop/parametric_plasma_source/source_sampling.so /openmc_workshop/tasks/task_3