# build with the following command
# sudo docker build -f Dockerfile_openmc_nndc -t openmcworkshop/openmc_nndc

FROM openmcworkshop/openmc

# install endf nuclear data

# clone data repository
RUN git clone https://github.com/openmc-dev/data.git

# run script that converts ACE data to hdf5 data
RUN python3 data/convert_nndc71.py --cleanup

ENV OPENMC_CROSS_SECTIONS=/nndc-b7.1-hdf5/cross_sections.xml
